//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.14 at 02:33:35 PM IST 
//


package com.aricent.eip.itsm.pojo;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="customerId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="engagementId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="reportedIssuetypeId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ciId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="priorityId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="requestor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="requestorEmail" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ticketSourceId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="supportTypeId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="createdBy" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="urgencyId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="impactId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="relatedCiIds" type="{pojo.itsm.eip.aricent.com}relatedCiIds"/>
 *         &lt;element name="faqs" type="{pojo.itsm.eip.aricent.com}faqs"/>
 *         &lt;element name="attachments" type="{pojo.itsm.eip.aricent.com}attachments"/>
 *         &lt;element name="reachedBy" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ticketCategory" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "customerId",
    "engagementId",
    "reportedIssuetypeId",
    "ciId",
    "title",
    "description",
    "priorityId",
    "requestor",
    "requestorEmail",
    "ticketSourceId",
    "supportTypeId",
    "createdBy",
    "urgencyId",
    "impactId",
    "relatedCiIds",
    "faqs",
    "attachments",
    "reachedBy",
    "ticketCategory"
})
@XmlRootElement(name = "getTicketDetailsRequest")
public class GetTicketDetailsRequest {

    @XmlElement(required = true)
    protected String name;
    protected int customerId;
    protected int engagementId;
    protected int reportedIssuetypeId;
    protected int ciId;
    @XmlElement(required = true)
    protected String title;
    @XmlElement(required = true)
    protected String description;
    protected int priorityId;
    @XmlElement(required = true)
    protected String requestor;
    @XmlElement(required = true)
    protected String requestorEmail;
    @XmlElement(required = true)
    protected String ticketSourceId;
    protected int supportTypeId;
    @XmlElement(required = true)
    protected String createdBy;
    @XmlElement(required = true)
    protected String urgencyId;
    @XmlElement(required = true)
    protected String impactId;
    @XmlList
    @XmlElement(type = Integer.class)
    protected List<Integer> relatedCiIds;
    @XmlList
    @XmlElement(required = true)
    protected List<String> faqs;
    @XmlList
    @XmlElement(required = true)
    protected List<String> attachments;
    @XmlElement(required = true)
    protected String reachedBy;
    @XmlElement(required = true)
    protected String ticketCategory;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the customerId property.
     * 
     */
    public int getCustomerId() {
        return customerId;
    }

    /**
     * Sets the value of the customerId property.
     * 
     */
    public void setCustomerId(int value) {
        this.customerId = value;
    }

    /**
     * Gets the value of the engagementId property.
     * 
     */
    public int getEngagementId() {
        return engagementId;
    }

    /**
     * Sets the value of the engagementId property.
     * 
     */
    public void setEngagementId(int value) {
        this.engagementId = value;
    }

    /**
     * Gets the value of the reportedIssuetypeId property.
     * 
     */
    public int getReportedIssuetypeId() {
        return reportedIssuetypeId;
    }

    /**
     * Sets the value of the reportedIssuetypeId property.
     * 
     */
    public void setReportedIssuetypeId(int value) {
        this.reportedIssuetypeId = value;
    }

    /**
     * Gets the value of the ciId property.
     * 
     */
    public int getCiId() {
        return ciId;
    }

    /**
     * Sets the value of the ciId property.
     * 
     */
    public void setCiId(int value) {
        this.ciId = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the priorityId property.
     * 
     */
    public int getPriorityId() {
        return priorityId;
    }

    /**
     * Sets the value of the priorityId property.
     * 
     */
    public void setPriorityId(int value) {
        this.priorityId = value;
    }

    /**
     * Gets the value of the requestor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestor() {
        return requestor;
    }

    /**
     * Sets the value of the requestor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestor(String value) {
        this.requestor = value;
    }

    /**
     * Gets the value of the requestorEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestorEmail() {
        return requestorEmail;
    }

    /**
     * Sets the value of the requestorEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestorEmail(String value) {
        this.requestorEmail = value;
    }

    /**
     * Gets the value of the ticketSourceId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTicketSourceId() {
        return ticketSourceId;
    }

    /**
     * Sets the value of the ticketSourceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTicketSourceId(String value) {
        this.ticketSourceId = value;
    }

    /**
     * Gets the value of the supportTypeId property.
     * 
     */
    public int getSupportTypeId() {
        return supportTypeId;
    }

    /**
     * Sets the value of the supportTypeId property.
     * 
     */
    public void setSupportTypeId(int value) {
        this.supportTypeId = value;
    }

    /**
     * Gets the value of the createdBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * Sets the value of the createdBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreatedBy(String value) {
        this.createdBy = value;
    }

    /**
     * Gets the value of the urgencyId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrgencyId() {
        return urgencyId;
    }

    /**
     * Sets the value of the urgencyId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrgencyId(String value) {
        this.urgencyId = value;
    }

    /**
     * Gets the value of the impactId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImpactId() {
        return impactId;
    }

    /**
     * Sets the value of the impactId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImpactId(String value) {
        this.impactId = value;
    }

    /**
     * Gets the value of the relatedCiIds property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relatedCiIds property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRelatedCiIds().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Integer }
     * 
     * 
     */
    public List<Integer> getRelatedCiIds() {
        if (relatedCiIds == null) {
            relatedCiIds = new ArrayList<Integer>();
        }
        return this.relatedCiIds;
    }

    /**
     * Gets the value of the faqs property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the faqs property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFaqs().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getFaqs() {
        if (faqs == null) {
            faqs = new ArrayList<String>();
        }
        return this.faqs;
    }

    /**
     * Gets the value of the attachments property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attachments property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttachments().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getAttachments() {
        if (attachments == null) {
            attachments = new ArrayList<String>();
        }
        return this.attachments;
    }

    /**
     * Gets the value of the reachedBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReachedBy() {
        return reachedBy;
    }

    /**
     * Sets the value of the reachedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReachedBy(String value) {
        this.reachedBy = value;
    }

    /**
     * Gets the value of the ticketCategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTicketCategory() {
        return ticketCategory;
    }

    /**
     * Sets the value of the ticketCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTicketCategory(String value) {
        this.ticketCategory = value;
    }

}
