//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.14 at 02:33:35 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "pojo.itsm.eip.aricent.com", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.aricent.eip.itsm.pojo;
